{
  "validation_time": "2025-11-10T14:34:24.233935",
  "validator_version": "1.0",
  "total_files": 6,
  "valid_files": [
    {
      "file": "modelos-3d/central-inteligente/chassi-principal.scad",
      "analysis": {
        "file_size": 5471,
        "total_lines": 187,
        "comment_lines": 34,
        "code_lines": 126,
        "empty_lines": 27,
        "modules": [
          "modulo_suporte"
        ],
        "functions": [],
        "variables": [
          "chassi_largura",
          "chassi_profundidade",
          "chassi_altura",
          "parede_altura",
          "parede_espessura",
          "base_espessura",
          "furo_diametro",
          "furo_profundidade",
          "margin",
          "furos",
          "esp32_pos",
          "esp32_size",
          "arduino_pos",
          "arduino_size",
          "rpi_pos",
          "rpi_size",
          "motor_pos",
          "motor_size",
          "cabo_diametro",
          "cabo_pos",
          "for (furo",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "for (j",
          "cylinder(h",
          "for (j",
          "cylinder(h",
          "linear_extrude(height",
          "text(label, size",
          "fonte_pos",
          "fonte_size",
          "for (i",
          "for (j",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"3dPot Central\", size",
          "linear_extrude(height",
          "text(\"Controle Inteligente\", size",
          "echo(\""
        ]
      }
    },
    {
      "file": "modelos-3d/central-inteligente/sistema-suportes-auxiliares.scad",
      "analysis": {
        "file_size": 13861,
        "total_lines": 498,
        "comment_lines": 77,
        "code_lines": 341,
        "empty_lines": 80,
        "modules": [
          "plataforma_giratoria",
          "organizador_cabos",
          "gabarito_esp32",
          "gabarito_arduino",
          "gabarito_raspberry",
          "gabarito_motor",
          "suporte_cabos_lateral",
          "separador_compartimentos"
        ],
        "functions": [],
        "variables": [
          "platforma_diametro",
          "platforma_altura",
          "eixo_diametro",
          "anel_rolamento_diametro",
          "anel_rolamento_altura",
          "organizador_largura",
          "organizador_profundidade",
          "organizador_altura",
          "furo_cabo_diametro",
          "num_furos",
          "gabarito_largura",
          "gabarito_profundidade",
          "gabarito_altura",
          "gabarito_esp32",
          "gabarito_arduino",
          "gabarito_raspberry",
          "gabarito_motor",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "angle",
          "x",
          "y",
          "cylinder(h",
          "for (i",
          "angle",
          "x",
          "y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"QC\", size",
          "for (i",
          "x",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (i",
          "x",
          "linear_extrude(height",
          "text(\"ESP32\", size",
          "linear_extrude(height",
          "text(\"Arduino\", size",
          "linear_extrude(height",
          "text(\"RPi\", size",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"ESP32\", size",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"Arduino\", size",
          "for (i",
          "y",
          "cylinder(h",
          "for (i",
          "y",
          "cylinder(h",
          "for (i",
          "x",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"RPi\", size",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"Motor\", size",
          "largura",
          "profundidade",
          "altura",
          "for (i",
          "y",
          "cylinder(h",
          "for (y",
          "cylinder(h",
          "for (i",
          "y",
          "largura",
          "profundidade",
          "altura",
          "compartment1",
          "compartment2",
          "compartment3",
          "for (comp",
          "for (x",
          "for (y",
          "cylinder(h",
          "compartment_labels",
          "compartment_x",
          "for (i",
          "linear_extrude(height",
          "text(compartment_labels[i], size",
          "echo(\""
        ]
      }
    },
    {
      "file": "modelos-3d/central-inteligente/suporte-arduino-esteira.scad",
      "analysis": {
        "file_size": 6579,
        "total_lines": 241,
        "comment_lines": 42,
        "code_lines": 165,
        "empty_lines": 34,
        "modules": [],
        "functions": [],
        "variables": [
          "arduino_largura",
          "arduino_profundidade",
          "arduino_altura",
          "suporte_largura",
          "suporte_profundidade",
          "suporte_altura",
          "pino_spacing",
          "num_pinos_lado",
          "conector_usb_largura",
          "conector_usb_profundidade",
          "furo_diametro",
          "furo_espacamento",
          "margin",
          "arduino_offset_x",
          "arduino_offset_y",
          "led_area_largura",
          "led_area_profundidade",
          "led_pos_x",
          "led_pos_y",
          "botao_diametro",
          "botao_pos_x",
          "botao_pos_y",
          "conector_diametro",
          "conectores_y",
          "conector_pos_x",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "for (y",
          "cylinder(h",
          "for (i",
          "x_pos",
          "y_pos",
          "cylinder(h",
          "for (i",
          "x_pos",
          "y_pos",
          "cylinder(h",
          "for (i",
          "for (j",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"Arduino\", size",
          "linear_extrude(height",
          "text(\"MOTOR\", size",
          "for (i",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "echo(\""
        ]
      }
    },
    {
      "file": "modelos-3d/central-inteligente/suporte-esp32-hx711.scad",
      "analysis": {
        "file_size": 4847,
        "total_lines": 180,
        "comment_lines": 32,
        "code_lines": 122,
        "empty_lines": 26,
        "modules": [],
        "functions": [],
        "variables": [
          "esp32_largura",
          "esp32_profundidade",
          "esp32_altura",
          "hx711_largura",
          "hx711_profundidade",
          "hx711_altura",
          "suporte_largura",
          "suporte_profundidade",
          "suporte_altura",
          "furo_diametro",
          "furo_espacamento",
          "margin",
          "esp32_offset_x",
          "esp32_offset_y",
          "hx711_offset_x",
          "hx711_offset_y",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (i",
          "linear_extrude(height",
          "text(\"ESP32\", size",
          "linear_extrude(height",
          "text(\"H X711\", size",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "echo(\""
        ]
      }
    },
    {
      "file": "modelos-3d/central-inteligente/suporte-raspberry-pi-qc.scad",
      "analysis": {
        "file_size": 8361,
        "total_lines": 301,
        "comment_lines": 46,
        "code_lines": 211,
        "empty_lines": 44,
        "modules": [],
        "functions": [],
        "variables": [
          "rpi_largura",
          "rpi_profundidade",
          "rpi_altura",
          "suporte_largura",
          "suporte_profundidade",
          "suporte_altura",
          "rpi_offset_x",
          "rpi_offset_y",
          "camera_largura",
          "camera_profundidade",
          "camera_offset_x",
          "camera_offset_y",
          "motor_largura",
          "motor_profundidade",
          "motor_altura",
          "motor_offset_x",
          "motor_offset_y",
          "led_ring_diametro",
          "led_ring_offset_x",
          "led_ring_offset_y",
          "furo_diametro",
          "furo_espacamento",
          "margin",
          "gpio_espacamento",
          "num_pinos_por_lado",
          "conector_usb_largura",
          "conector_usb_profundidade",
          "conector_eth_largura",
          "conector_eth_profundidade",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "for (i",
          "y_pos",
          "cylinder(h",
          "for (i",
          "y_pos",
          "cylinder(h",
          "for (i",
          "x_pos",
          "cylinder(h",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "cylinder(h",
          "for (i",
          "angle",
          "x",
          "y",
          "cylinder(h",
          "ventilador_diametro",
          "ventilador_offset_x",
          "ventilador_offset_y",
          "cylinder(h",
          "cylinder(h",
          "for (angle",
          "x",
          "y",
          "cylinder(h",
          "for (i",
          "cylinder(h",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "linear_extrude(height",
          "text(\"RPi QC\", size",
          "linear_extrude(height",
          "text(\"MOTOR\", size",
          "linear_extrude(height",
          "text(\"LEDs\", size",
          "for (i",
          "cylinder(h",
          "for (x",
          "for (y",
          "cylinder(h",
          "cylinder(h",
          "echo(\""
        ]
      }
    }
  ],
  "error_files": [
    {
      "file": "modelos-3d/central-inteligente/suporte-fonte-conectores.scad",
      "error": "ERROR: Parser error: syntax error in file modelos-3d/central-inteligente/suporte-fonte-conectores.scad, line 106\nCan't parse file 'modelos-3d/central-inteligente/suporte-fonte-conectores.scad'!\n\n",
      "output": ""
    }
  ],
  "warning_files": [],
  "stl_generated": [
    {
      "scad_file": "modelos-3d/central-inteligente/chassi-principal.scad",
      "stl_file": "modelos-3d/central-inteligente/chassi-principal.stl",
      "stl_size": 1541064
    },
    {
      "scad_file": "modelos-3d/central-inteligente/sistema-suportes-auxiliares.scad",
      "stl_file": "modelos-3d/central-inteligente/sistema-suportes-auxiliares.stl",
      "stl_size": 1504523
    },
    {
      "scad_file": "modelos-3d/central-inteligente/suporte-arduino-esteira.scad",
      "stl_file": "modelos-3d/central-inteligente/suporte-arduino-esteira.stl",
      "stl_size": 700861
    },
    {
      "scad_file": "modelos-3d/central-inteligente/suporte-esp32-hx711.scad",
      "stl_file": "modelos-3d/central-inteligente/suporte-esp32-hx711.stl",
      "stl_size": 513297
    },
    {
      "scad_file": "modelos-3d/central-inteligente/suporte-raspberry-pi-qc.scad",
      "stl_file": "modelos-3d/central-inteligente/suporte-raspberry-pi-qc.stl",
      "stl_size": 798328
    }
  ],
  "stl_failed": []
}